# alertmanager.yml

route:
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  # Receptor por defecto para alertas que no coincidan con las rutas de remediación.
  # --- MEJORA: Se añade un receptor de notificaciones para visibilidad del equipo ---
  receiver: 'slack-notifications'

  routes:
    # --- RUTA PARA REMEDIACIÓN AUTOMÁTICA ---
    # Si una alerta tiene la etiqueta 'remediation', se envía al webhook de Ansible.
    - receiver: 'ansible_remediador'
      # --- MEJORA: Se usa 'matchers' que es más flexible ---
      # Coincide si la etiqueta 'remediation' existe.
      matchers:
        - remediation!=""
      # Continúa evaluando otras rutas hijas si esta coincide.
      continue: true

    # --- SUB-RUTAS PARA REMEDIACIONES ESPECÍFICAS ---
    # Estas son rutas hijas de la anterior. Solo se evaluarán si la alerta ya coincidió
    # con 'remediation!=""'. Aquí se podría añadir lógica más específica si fuera necesario,
    # aunque con el playbook actual no es estrictamente necesario.
    - receiver: 'ansible_remediador'
      matchers:
        - remediation="cpu"

    - receiver: 'ansible_remediador'
      matchers:
        - remediation="ram"

receivers:
  - name: 'ansible_remediador'
    webhook_configs:
      # --- MEJORA: URL única para el playbook de remediación genérico ---
      - url: 'http://127.0.0.1:9000/hooks/remediar-servidor'
        send_resolved: true

  # --- NUEVO RECEPTOR: Notificaciones a Slack (o tu sistema preferido) ---
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK_URL' # ¡Reemplazar con tu URL!
        channel: '#alertas-produccion'
        send_resolved: true
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} para {{ .CommonLabels.instance }}'
        text: >-
          {{ range .Alerts }}
            *Alerta:* {{ .Annotations.summary }}
            *Descripción:* {{ .Annotations.description }}
            *Detalles:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}
