# La sección 'route' es el árbol de decisión principal para las alertas.
route:
  # Agrupa las alertas por nombre y servidor para evitar notificaciones repetidas.
  group_by: ['alertname', 'instance']
  
  # Cuánto esperar para agrupar notificaciones para el mismo grupo.
  group_wait: 30s
  
  # Cuánto esperar antes de enviar una notificación para un grupo nuevo.
  group_interval: 5m
  
  # Cuánto esperar para repetir una notificación si la alerta persiste.
  repeat_interval: 1h
  
  # --- CAMBIO PRINCIPAL ---
  # El receptor por defecto ahora es 'ansible_remediador'.
  # Cualquier alerta que no coincida con una de las sub-rutas de abajo, irá aquí.
  receiver: 'ansible_remediador'

  # 'routes' es una lista de reglas de enrutamiento más específicas.
  # Alertmanager las evalúa en orden y se detiene en la primera que coincida.
  routes:
    # --- RUTA PARA ALERTAS DE CPU ---
    # Si una alerta tiene la etiqueta 'remediation: cpu'...
    - receiver: 'remediacion-cpu'
      match:
        remediation: cpu

    # --- RUTA PARA ALERTAS DE RAM ---
    # Si una alerta tiene la etiqueta 'remediation: ram'...
    - receiver: 'remediacion-ram'
      match:
        remediation: ram

# La sección 'receivers' define qué es y qué hace cada receptor.
receivers:
  # Definición del receptor por defecto.
  - name: 'ansible_remediador'
    webhook_configs:
      # Envía a un hook genérico. Deberás crear este hook en tu archivo hooks.json
      # para manejar cualquier otra alerta (ej. enviar un email o una notificación a Slack).
      - url: 'http://127.0.0.1:9000/hooks/alerta-generica'

  # Definición del receptor para la remediación específica de CPU.
  - name: 'remediacion-cpu'
    webhook_configs:
      # URL del endpoint en nuestro servicio 'webhook' para el playbook de CPU.
      - url: 'http://127.0.0.1:9000/hooks/remediar-cpu'

  # Definición del receptor para la remediación específica de RAM.
  - name: 'remediacion-ram'
    webhook_configs:
      # URL del endpoint en nuestro servicio 'webhook' para el playbook de RAM.
      - url: 'http://127.0.0.1:9000/hooks/remediar-ram'
