# prometheus.yml

global:
  scrape_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # --- OPTIMIZACIÓN ---
  # Se reemplaza la configuración estática por el descubrimiento de servicios basado en archivos.
  # Esto permite añadir o quitar servidores modificando únicamente el archivo 'targets.json',
  # sin necesidad de recargar la configuración de Prometheus.
  - job_name: 'jboss_servers'
    file_sd_configs:
      - files:
          - 'targets.json'
        # Opcional: con qué frecuencia Prometheus debe releer el archivo.
        refresh_interval: 1m
